[package]
name = "nameres"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
span.path = "../span"
ident.path = "../ident"
errors.path = "../errors"
ast.path = "../ast"
hir.path = "../hir"
# External
im-rc = "15.1.0"
foldhash = "0.2.0"
derive_more = { version = "2.1.1", features = ["display"] }
smallvec = { version = "1.15.1", features = [
    "union",
    "const_generics",
    "const_new",
] }
itertools = "0.14.0"

[dev-dependencies]
# Internal
parse = { path = "../parse", features = ["test"] }
lex = { path = "../lex", features = ["test"] }
# External

[lints]
workspace = true

[features]
test = []
