[package]
name = "hir"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
ident.path = "../ident"
# External
derive_more = { version = "2.1.1", features = [
    "display",
    "from",
    "into_iterator",
] }
slotmap = "1.1.1"
smallvec = { version = "1.15.1", features = [
    "union",
    "const_generics",
    "const_new",
] }


[lints]
workspace = true
