[package]
name = "parse"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
lex = { path = "../lex" }
ast = { path = "../ast" }
span = { path = "../span" }
ident = { path = "../ident" }
# External
string-interner = "0.19.0"
thiserror = "2.0.18"
pretty_assertions = { version = "1.4.1", optional = true }

[dev-dependencies]
# Internal
lex = { path = "../lex", features = ["test"] }
# External
pretty_assertions = "1.4.1"
itertools = "0.14.0"
proptest = "1.11.0"

[lints]
workspace = true

[features]
test = ["dep:pretty_assertions"]
