[package]
name = "parse"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
span.path = "../span"
ident.path = "../ident"
lex.path = "../lex"
ast.path = "../ast"
errors.path = "../errors"
# External
string-interner = "0.19.0"
itertools = "0.14.0"
pretty_assertions = { version = "1.4.1", optional = true }
derive_more = { version = "2.1.1", features = ["from", "display"] }
smallvec = { version = "1.15.1", features = [
    "union",
    "const_generics",
    "const_new",
] }

[dev-dependencies]
# Internal
lex = { path = "../lex", features = ["test"] }
# External
pretty_assertions = "1.4.1"
proptest = "1.11.0"

[lints]
workspace = true

[features]
test = ["dep:pretty_assertions"]
