[workspace]
resolver = "3"
members = [
    "compile",
    "span",
    "ident",
    "errors",
    "lex",
    "parse",
    "ast",
    "nameres",
    # "typecheck",
]

[workspace.lints.clippy]
must_use_candidate = "allow"
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

[workspace.lints.rustc]
missing_docs = "warn"
