[package]
name = "nameres"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
ident.path = "../ident"
errors.path = "../errors"
package.path = "../package"
irs.path = "../irs"
# External
imbl = "7.0.0"
foldhash = "0.2.0"
derive_more = { version = "2.1.1", features = ["display"] }
itertools = "0.14.0"
parse = { path = "../parse", features = ["test"], optional = true }

[dev-dependencies]
# Internal
parse = { path = "../parse", features = ["test"] }
# External

[lints]
workspace = true

[features]
test = ["dep:parse"]
