[package]
name = "nameres"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
ident.path = "../ident"
errors.path = "../errors"
irs.path = "../irs"
# External
slotmap = "1.1.1"
foldhash = "0.2.0"
itertools = "0.15.0"
parse = { path = "../parse", features = ["test"], optional = true }

[lints]
workspace = true

[features]
test = ["dep:parse"]
