[package]
name = "typecheck"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
span.path = "../span"
ident.path = "../ident"
errors.path = "../errors"
hir.path = "../hir"
# External
ego-tree = "0.11.0"
ena = "0.14.3"
fnv = "1.0.7"
itertools = "0.14.0"
im = "15.1.0"
derive_more = { version = "2.1.1", features = ["display"] }

[dev-dependencies]
# Internal
parse = { path = "../parse", features = ["test"] }
lex = { path = "../lex", features = ["test"] }

[lints]
workspace = true
