[package]
name = "typecheck"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal

ident.path = "../ident"
errors.path = "../errors"
hir.path = "../hir"
# External
ena = "0.14.3"
itertools = "0.14.0"
derive_more = { version = "2.1.1", features = ["display", "from"] }
slotmap = "1.1.1"

[dev-dependencies]
# Internal
parse = { path = "../parse", features = ["test"] }
nameres = { path = "../nameres", features = ["test"] }

[lints]
workspace = true
