[package]
name = "codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
ident.path = "../ident"
hir.path = "../hir"
errors.path = "../errors"
# External
inkwell = { version = "0.9.0", features = ["llvm22-1"] }
slotmap = "1.1.1"

[dev-dependencies]
# Internal
parse.path = "../parse"
nameres.path = "../nameres"
typecheck.path = "../typecheck"

[lints]
workspace = true
