[package]
name = "compile"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
span.path = "../span"
errors.path = "../errors"
ast.path = "../ast"
parse.path = "../parse"
nameres.path = "../nameres"
typecheck.path = "../typecheck"
codegen.path = "../codegen"
# External
yansi = "1.0.1"
clap = { version = "4.6.1", features = ["derive"] }

[lints]
workspace = true
