[package]
name = "compile"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
span = { path = "../span" }
lex = { path = "../lex" }
ast = { path = "../ast" }
parse = { path = "../parse" }
#typecheck = { path = "../typecheck" }
# External
anyhow = "1.0.100"
yansi = "1.0.1"

[lints]
workspace = true
