[package]
name = "compile"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
errors.path = "../errors"
package.path = "../package"
ast.path = "../ast"
parse.path = "../parse"
nameres.path = "../nameres"
typecheck.path = "../typecheck"
codegen_llvm.path = "../codegen_llvm"
# External
yansi = "1.0.1"
argh = { version = "0.1.19", features = ["help"], default-features = false }
slotmap = "1.1.1"

[lints]
workspace = true
