[package]
name = "lower"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
ident.path = "../ident"
errors.path = "../errors"
package.path = "../package"
hir.path = "../hir"
mir.path = "../mir"
# External
slotmap = "1.1.1"

[dev-dependencies]
# Internal
# External

[lints]
workspace = true

[features]
