[package]
name = "ast"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
ident.path = "../ident"
# External
derive_more = { version = "2.1.1", features = ["display"] }
itertools = "0.14.0"
smallvec = { version = "1.15.1", features = [
    "union",
    "const_generics",
    "const_new",
] }

[dev-dependencies]
# Internal
parse = { path = "../parse", features = ["test"] }

[lints]
workspace = true
