[package]
name = "parse"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
ident.path = "../ident"
errors.path = "../errors"
irs.path = "../irs"
# External
itertools = "0.15.0"
derive_more = { version = "2.1.1", features = ["from", "display"] }
logos = "0.16.1"

[dev-dependencies]
# Internal
# External
pretty_assertions = "1.4.1"
proptest = "1.11.0"
proptest-derive = "0.8.0"

[lints]
workspace = true
