[package]
name = "codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
ident.path = "../ident"
irs.path = "../irs"
# External
inkwell = { version = "0.9.0", features = ["llvm22-1"] }
slotmap = "1.1.1"

[dev-dependencies]
# Internal
errors.path = "../errors"
parse.path = "../parse"
nameres = { path = "../nameres", features = ["test"] }
typecheck.path = "../typecheck"
lower.path = "../lower"

[lints]
workspace = true
