[package]
name = "irs"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
ident.path = "../ident"
package.path = "../package"
# External
derive_more = { version = "2.1.1", features = [
    "display",
    "from",
    "into_iterator",
] }
itertools = "0.14.0"
foldhash = "0.2.0"
slotmap = "1.1.1"

[lints]
workspace = true
