use crate::span;
use std::fmt::Display;

span! {TokenType as Token}
#[derive(PartialEq, Eq, Debug, Clone, Copy)]
pub enum TokenType {
    // Literals
    IntLit,
    FloatLit,
    StringLit,
    CharLit,
    // Delimiters
    LParen,
    RParen,
    Indent,
    Dedent,
    LBracket,
    RBracket,
    // Symbols
    Eq,
    Ampersand,
    Pipe,
    Bang,
    LAngle,
    RAngle,
    Plus,
    Minus,
    Times,
    FSlash,
    BSlash,
    Dot,
    Comma,
    Colon,
    Semicolon,
    Underscore,
    Arrow,
    // Operators
    Exponent,
    And,
    Or,
    Xor,
    Eqq,
    Neq,
    Leq,
    Geq,
    // Keywords
    Int,
    UInt,
    Byte,
    Float,
    Bool,
    Char,
    Let,
    Mut,
    Const,
    Fn,
    Struct,
    Enum,
    If,
    Then,
    Else,
    For,
    In,
    While,
    Do,
    Match,
    With,
    True,
    False,
    // Misc
    Ident,
    Error,
    Eof,
}

impl Display for TokenType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::IntLit => "int literal",
                Self::FloatLit => "float literal",
                Self::StringLit => "string literal",
                Self::CharLit => "char literal",
                Self::LParen => "(",
                Self::RParen => ")",
                Self::Indent => "{",
                Self::Dedent => "}",
                Self::LBracket => "[",
                Self::RBracket => "]",
                Self::Eq => "=",
                Self::Ampersand => "&",
                Self::Pipe => "|",
                Self::Bang => "!",
                Self::LAngle => "<",
                Self::RAngle => ">",
                Self::Plus => "+",
                Self::Minus => "-",
                Self::Times => "*",
                Self::FSlash => "/",
                Self::BSlash => "\\",
                Self::Dot => ".",
                Self::Comma => ",",
                Self::Colon => ":",
                Self::Semicolon => ";",
                Self::Underscore => "_",
                Self::Arrow => "->",
                Self::Exponent => "**",
                Self::And => "&&",
                Self::Or => "||",
                Self::Xor => "^",
                Self::Eqq => "==",
                Self::Neq => "!=",
                Self::Leq => "<=",
                Self::Geq => ">=",
                Self::Int => "Int",
                Self::UInt => "UInt",
                Self::Byte => "Byte",
                Self::Float => "Float",
                Self::Bool => "Bool",
                Self::Char => "Char",
                Self::Let => "let",
                Self::Mut => "mut",
                Self::Const => "const",
                Self::Fn => "fn",
                Self::Struct => "struct",
                Self::Enum => "enum",
                Self::If => "if",
                Self::Then => "then",
                Self::Else => "else",
                Self::For => "for",
                Self::In => "in",
                Self::While => "while",
                Self::Do => "do",
                Self::Match => "match",
                Self::With => "with",
                Self::True => "true",
                Self::False => "false",
                Self::Ident => "identifier",
                Self::Error => "ERROR",
                Self::Eof => "eof",
            }
        )
    }
}
