use std::fmt::Display;

#[derive(PartialEq, Debug, Clone)]
pub enum Token {
    // Literals
    IntLit(i64),
    FloatLit(f64),
    StringLit(String),
    CharLit(char),
    // Delimiters
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    // Symbols
    Eq,
    Ampersand,
    Pipe,
    Bang,
    LAngle,
    RAngle,
    Plus,
    Minus,
    Times,
    FSlash,
    BSlash,
    Dot,
    Comma,
    Colon,
    Semicolon,
    Underscore,
    Arrow,
    // Operators
    Exponent,
    And,
    Or,
    Xor,
    Eqq,
    Neq,
    Leq,
    Geq,
    // Keywords
    Let,
    Mut,
    Const,
    Fn,
    Struct,
    Enum,
    If,
    Else,
    Match,
    True,
    False,
    // Misc
    Ident(String),
    Error { start: usize, end: usize },
    Eof,
}

impl Display for Token {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Token::IntLit(_) => "int literal",
                Token::FloatLit(_) => "float literal",
                Token::StringLit(_) => "string literal",
                Token::CharLit(_) => "char literal",
                Token::LParen => "(",
                Token::RParen => ")",
                Token::LBrace => "{",
                Token::RBrace => "}",
                Token::LBracket => "[",
                Token::RBracket => "]",
                Token::Eq => "=",
                Token::Ampersand => "&",
                Token::Pipe => "|",
                Token::Bang => "!",
                Token::LAngle => "<",
                Token::RAngle => ">",
                Token::Plus => "+",
                Token::Minus => "-",
                Token::Times => "*",
                Token::FSlash => "/",
                Token::BSlash => "\\",
                Token::Dot => ".",
                Token::Comma => ",",
                Token::Colon => ":",
                Token::Semicolon => ";",
                Token::Underscore => "_",
                Token::Arrow => "->",
                Token::Exponent => "**",
                Token::And => "&&",
                Token::Or => "||",
                Token::Xor => "^",
                Token::Eqq => "==",
                Token::Neq => "!=",
                Token::Leq => "<=",
                Token::Geq => ">=",
                Token::Let => "let",
                Token::Mut => "mut",
                Token::Const => "const",
                Token::Fn => "fn",
                Token::Struct => "struct",
                Token::Enum => "enum",
                Token::If => "if",
                Token::Else => "else",
                Token::Match => "match",
                Token::True => "true",
                Token::False => "false",
                Token::Ident(i) => return write!(f, "identifier {i}"),
                Token::Error { start, end } => return write!(f, "ERROR start:{start} end:{end}"),
                Token::Eof => "eof",
            }
        )
    }
}
